create or replace database RETAIL_DW;

create or replace schema RETAIL_DW.CONTROL;

create or replace TABLE RETAIL_DW.CONTROL.ETL_PIPELINE_STATUS (
	PIPELINE_NAME VARCHAR(16777216),
	LAST_RUN TIMESTAMP_NTZ(9),
	STATUS VARCHAR(16777216),
	ROWS_PROCESSED NUMBER(38,0),
	ERROR_MESSAGE VARCHAR(16777216)
);
CREATE OR REPLACE PROCEDURE RETAIL_DW.CONTROL.SP_PROCESS_CUSTOMER()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    CALL RETAIL_DW.RAW.SP_REFRESH_CUSTOMER();
    CALL RETAIL_DW.STAGING.SP_BUILD_DIM_CUSTOMER();

    INSERT INTO RETAIL_DW.CONTROL.ETL_PIPELINE_STATUS
    (
        PIPELINE_NAME,
        LAST_RUN,
        STATUS,
        ERROR_MESSAGE
    )
    VALUES
    (
        ''PROCESS CUSTOMER'',
        CURRENT_TIMESTAMP(),
        ''SUCCESS'',
        NULL
    );

    RETURN ''PROCESS CUSTOMER COMPLETED'';

EXCEPTION
    WHEN OTHER THEN

        INSERT INTO RETAIL_DW.CONTROL.ETL_PIPELINE_STATUS
        (
            PIPELINE_NAME,
            LAST_RUN,
            STATUS,
            ERROR_MESSAGE
        )
        VALUES
        (
            ''PROCESS CUSTOMER'',
            CURRENT_TIMESTAMP(),
            ''FAILED'',
            SQLERRM
        );

        RETURN ''FAILED: '' || SQLERRM;

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.CONTROL.SP_PROCESS_PRODUCT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    CALL RETAIL_DW.RAW.SP_REFRESH_PRODUCT();
    CALL RETAIL_DW.STAGING.SP_BUILD_DIM_PRODUCT();

    INSERT INTO RETAIL_DW.CONTROL.ETL_PIPELINE_STATUS
    (
        PIPELINE_NAME,
        LAST_RUN,
        STATUS,
        ERROR_MESSAGE
    )
    VALUES
    (
        ''PROCESS PRODUCT'',
        CURRENT_TIMESTAMP(),
        ''SUCCESS'',
        NULL
    );

    RETURN ''PROCESS PRODUCT COMPLETED'';

EXCEPTION
    WHEN OTHER THEN

        INSERT INTO RETAIL_DW.CONTROL.ETL_PIPELINE_STATUS
        (
            PIPELINE_NAME,
            LAST_RUN,
            STATUS,
            ERROR_MESSAGE
        )
        VALUES
        (
            ''PROCESS PRODUCT'',
            CURRENT_TIMESTAMP(),
            ''FAILED'',
            SQLERRM
        );

        RETURN ''FAILED: '' || SQLERRM;

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.CONTROL.SP_PROCESS_SALES()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    CALL RETAIL_DW.RAW.SP_REFRESH_ORDERS();
    CALL RETAIL_DW.RAW.SP_REFRESH_ORDER_ITEMS();

    -- CALL RETAIL_DW.STAGING.SP_BUILD_FACT_SALES();

    INSERT INTO RETAIL_DW.CONTROL.ETL_PIPELINE_STATUS
    (
        PIPELINE_NAME,
        LAST_RUN,
        STATUS,
        ERROR_MESSAGE
    )
    VALUES
    (
        ''PROCESS SALES'',
        CURRENT_TIMESTAMP(),
        ''SUCCESS'',
        NULL
    );

    RETURN ''PROCESS SALES COMPLETED'';

EXCEPTION
    WHEN OTHER THEN

        INSERT INTO RETAIL_DW.CONTROL.ETL_PIPELINE_STATUS
        (
            PIPELINE_NAME,
            LAST_RUN,
            STATUS,
            ERROR_MESSAGE
        )
        VALUES
        (
            ''PROCESS SALES'',
            CURRENT_TIMESTAMP(),
            ''FAILED'',
            SQLERRM
        );

        RETURN ''FAILED: '' || SQLERRM;

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.CONTROL.SP_RUN_FULL_ETL()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    CALL RETAIL_DW.RAW.SP_REFRESH_CUSTOMER();

    CALL RETAIL_DW.RAW.SP_REFRESH_PRODUCT();
    
    CALL RETAIL_DW.RAW.SP_REFRESH_ORDERS();
    
    CALL RETAIL_DW.RAW.SP_REFRESH_ORDER_ITEMS();
    
    CALL RETAIL_DW.STAGING.SP_BUILD_DIM_CUSTOMER();
    
    CALL RETAIL_DW.STAGING.SP_BUILD_DIM_PRODUCT();
    
    -- CALL RETAIL_DW.STAGING.SP_BUILD_FACT_SALES();

    INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
    (
        PIPELINE_NAME,
        RUN_TIME,
        STATUS
    )
    VALUES
    (
        ''FULL ETL'',
        CURRENT_TIMESTAMP(),
        ''SUCCESS''
    );

    RETURN ''FULL ETL COMPLETED'';

EXCEPTION
    WHEN OTHER THEN

        INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
        (
            PIPELINE_NAME,
            RUN_TIME,
            STATUS
        )
        VALUES
        (
            ''FULL ETL'',
            CURRENT_TIMESTAMP(),
            ''FAILED''
        );

        RETURN ''FAILED: '' || SQLERRM;

END;
';
create or replace pipe RETAIL_DW.CONTROL.PIPE_CUSTOMER auto_ingest=false as COPY INTO RETAIL_DW.RAW.CUSTOMER_RAW
FROM @RETAIL_DW.RAW.RETAIL_STAGE/raw/customers/
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_DW.RAW.CSV_FORMAT');
create or replace pipe RETAIL_DW.CONTROL.PIPE_ORDERS auto_ingest=false as COPY INTO RETAIL_DW.RAW.SALES_RAW
FROM @RETAIL_DW.RAW.RETAIL_STAGE/raw/sales/orders.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_DW.RAW.CSV_FORMAT');
create or replace pipe RETAIL_DW.CONTROL.PIPE_ORDER_ITEMS auto_ingest=false as COPY INTO RETAIL_DW.RAW.SALES_ITEM_RAW
FROM @RETAIL_DW.RAW.RETAIL_STAGE/raw/sales/order_items.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_DW.RAW.CSV_FORMAT');
create or replace pipe RETAIL_DW.CONTROL.PIPE_PRODUCT auto_ingest=false as COPY INTO RETAIL_DW.RAW.PRODUCT_RAW
FROM @RETAIL_DW.RAW.RETAIL_STAGE/raw/products/
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_DW.RAW.CSV_FORMAT');
create or replace task RETAIL_DW.CONTROL.MASTER_ETL_TASK
	warehouse=RETAIL_WH
	schedule='USING CRON 0 * * * * UTC'
	as CALL CONTROL.SP_RUN_FULL_ETL();
create or replace schema RETAIL_DW.MART;

create or replace TABLE RETAIL_DW.MART.DATA_QUALITY_LOG (
	CHECK_NAME VARCHAR(16777216),
	CHECK_TIME TIMESTAMP_NTZ(9),
	FAILED_RECORDS NUMBER(38,0)
);
create or replace TABLE RETAIL_DW.MART.DIM_CUSTOMER (
	CUSTOMER_ID NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(16777216),
	CITY VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	CREATEDDATE DATE
);
create or replace TABLE RETAIL_DW.MART.DIM_DATE (
	DATE_KEY DATE,
	YEAR NUMBER(4,0),
	QUARTER NUMBER(2,0),
	MONTH NUMBER(2,0),
	MONTH_NAME VARCHAR(3)
);
create or replace TABLE RETAIL_DW.MART.DIM_PRODUCT (
	PRODUCTID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	UNITPRICE NUMBER(18,2)
);
create or replace TABLE RETAIL_DW.MART.ETL_AUDIT_LOG (
	PIPELINE_NAME VARCHAR(16777216),
	RUN_TIME TIMESTAMP_NTZ(9),
	RECORD_COUNT NUMBER(38,0),
	STATUS VARCHAR(16777216)
);
create or replace TABLE RETAIL_DW.MART.FACT_SALES (
	ORDERID NUMBER(38,0),
	ORDERDATE DATE,
	CUSTOMERID NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	QTY NUMBER(18,2),
	PRICE NUMBER(18,2),
	LINE_AMOUNT NUMBER(36,4),
	REPID NUMBER(38,0)
);
create or replace view RETAIL_DW.MART.VW_EXECUTIVE_KPI(
	TOTAL_ORDERS,
	TOTAL_CUSTOMERS,
	TOTAL_REVENUE,
	AVG_ORDER_VALUE
) as
SELECT
    COUNT(DISTINCT ORDERID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMERID) AS TOTAL_CUSTOMERS,
    SUM(LINE_AMOUNT) AS TOTAL_REVENUE,
    AVG(LINE_AMOUNT) AS AVG_ORDER_VALUE
FROM MART.FACT_SALES;
create or replace view RETAIL_DW.MART.VW_PRODUCT_PERFORMANCE(
	PRODUCTID,
	TOTAL_REVENUE,
	TOTAL_QTY
) as
SELECT
    PRODUCTID,
    SUM(LINE_AMOUNT) AS TOTAL_REVENUE,
    SUM(QTY) AS TOTAL_QTY
FROM MART.FACT_SALES
GROUP BY PRODUCTID;
create or replace view RETAIL_DW.MART.VW_SALES_ANALYTICS(
	ORDERID,
	ORDERDATE,
	MONTH_NAME,
	CUSTOMER_NAME,
	PRODUCT_NAME,
	CATEGORY,
	QTY,
	PRICE,
	LINE_AMOUNT
) as
SELECT
    F.ORDERID,
    F.ORDERDATE,
    D.MONTH_NAME,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    P.CATEGORY,
    F.QTY,
    F.PRICE,
    F.LINE_AMOUNT
FROM MART.FACT_SALES F
JOIN MART.DIM_CUSTOMER C
    ON F.CUSTOMERID = C.CUSTOMER_ID
JOIN MART.DIM_PRODUCT P
    ON F.PRODUCTID = P.PRODUCTID
JOIN MART.DIM_DATE D
    ON F.ORDERDATE = D.DATE_KEY;
create or replace schema RETAIL_DW.PUBLIC;

create or replace schema RETAIL_DW.RAW;

create or replace TABLE RETAIL_DW.RAW.CUSTOMER_RAW (
	CUSTOMER_ID NUMBER(38,0),
	CUSTOMERNAME VARCHAR(16777216),
	CITY VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	CREATEDDATE DATE,
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9)
);
create or replace TABLE RETAIL_DW.RAW.PRODUCT_RAW (
	PRODUCTID NUMBER(38,0),
	PRODUCTNAME VARCHAR(16777216),
	UNITPRICE NUMBER(18,2),
	CATEGORY VARCHAR(16777216)
);
create or replace TABLE RETAIL_DW.RAW.SALES_ITEM_RAW (
	ITEMID NUMBER(38,0),
	ORDERID NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	QTY NUMBER(18,2),
	PRICE NUMBER(18,2)
);
create or replace TABLE RETAIL_DW.RAW.SALES_RAW (
	ORDERID NUMBER(38,0),
	CUSTOMERID NUMBER(38,0),
	REPID NUMBER(38,0),
	ORDERDATE DATE,
	STATUS VARCHAR(50)
);
CREATE OR REPLACE FILE FORMAT RETAIL_DW.RAW.CSV_FORMAT
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
;
CREATE OR REPLACE PROCEDURE RETAIL_DW.RAW.LOAD_CUSTOMER_ETL()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN

    INSERT INTO MART.ETL_AUDIT_LOG
    SELECT
        ''CUSTOMER_LOAD'',
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP(),
        COUNT(*),
        ''SUCCESS''
    FROM STAGING.STG_CUSTOMER;

    RETURN ''CUSTOMER LOAD COMPLETED'';

END';
CREATE OR REPLACE PROCEDURE RETAIL_DW.RAW.SP_REFRESH_CUSTOMER()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

MERGE INTO STAGING.STG_CUSTOMER T
USING (
    SELECT
        CUSTOMER_ID,
        CUSTOMERNAME,
        CITY,
        PHONE,
        STATUS,
        CREATEDDATE
    FROM CUSTOMER_STREAM
) S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED THEN
UPDATE SET
    CUSTOMER_NAME = S.CUSTOMERNAME,
    CITY = S.CITY,
    PHONE = S.PHONE,
    STATUS = S.STATUS

WHEN NOT MATCHED THEN
INSERT (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PHONE,
    STATUS,
    CREATEDDATE
)
VALUES (
    S.CUSTOMER_ID,
    S.CUSTOMERNAME,
    S.CITY,
    S.PHONE,
    S.STATUS,
    S.CREATEDDATE
);

INSERT INTO MART.ETL_AUDIT_LOG
SELECT
    ''CUSTOMER_REFRESH'',
    CURRENT_TIMESTAMP(),
    COUNT(*),
    ''SUCCESS''
FROM CUSTOMER_STREAM;

RETURN ''SUCCESS'';

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.RAW.SP_REFRESH_ORDERS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

MERGE INTO RETAIL_DW.STAGING.STG_ORDERS T
USING (
    SELECT
        ORDERID,
        CUSTOMERID,
        REPID,
        ORDERDATE,
        STATUS
    FROM ORDERS_STREAM
) S
ON T.ORDERID = S.ORDERID

WHEN MATCHED THEN
UPDATE SET
    STATUS = S.STATUS

WHEN NOT MATCHED THEN
INSERT (
    ORDERID,
    CUSTOMERID,
    REPID,
    ORDERDATE,
    STATUS
)
VALUES (
    S.ORDERID,
    S.CUSTOMERID,
    S.REPID,
    S.ORDERDATE,
    S.STATUS
);

INSERT INTO MART.ETL_AUDIT_LOG
SELECT
    ''ORDERS_REFRESH'',
    CURRENT_TIMESTAMP(),
    COUNT(*),
    ''SUCCESS''
FROM ORDERS_STREAM;

RETURN ''SUCCESS'';

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.RAW.SP_REFRESH_ORDER_ITEMS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    MERGE INTO RETAIL_DW.STAGING.STG_ORDER_ITEMS T
    USING (
        SELECT
            ITEMID,
            ORDERID,
            PRODUCTID,
            QTY,
            PRICE,
            METADATA$ACTION
        FROM RETAIL_DW.RAW.ORDER_ITEMS_STREAM
    ) S
    ON T.ITEMID = S.ITEMID

    WHEN MATCHED
         AND S.METADATA$ACTION = ''DELETE''
    THEN DELETE

    WHEN MATCHED
         AND S.METADATA$ACTION <> ''DELETE''
    THEN
        UPDATE SET
            ORDERID   = S.ORDERID,
            PRODUCTID = S.PRODUCTID,
            QTY       = S.QTY,
            PRICE     = S.PRICE

    WHEN NOT MATCHED
         AND S.METADATA$ACTION <> ''DELETE''
    THEN
        INSERT (
            ITEMID,
            ORDERID,
            PRODUCTID,
            QTY,
            PRICE
        )
        VALUES (
            S.ITEMID,
            S.ORDERID,
            S.PRODUCTID,
            S.QTY,
            S.PRICE
        );

    INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
    (
        PIPELINE_NAME,
        RUN_TIME,
        RECORD_COUNT,
        STATUS
    )
    SELECT
        ''ORDER_ITEMS_REFRESH'',
        CURRENT_TIMESTAMP(),
        COUNT(*),
        ''SUCCESS''
    FROM RETAIL_DW.RAW.ORDER_ITEMS_STREAM;

    RETURN ''SUCCESS'';

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.RAW.SP_REFRESH_PRODUCT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

MERGE INTO RETAIL_DW.STAGING.STG_PRODUCT T
USING (
    SELECT
        PRODUCTID,
        PRODUCTNAME,
        UNITPRICE,
        CATEGORY
    FROM PRODUCT_STREAM
) S
ON T.PRODUCTID = S.PRODUCTID

WHEN MATCHED THEN
UPDATE SET
    PRODUCT_NAME = S.PRODUCTNAME,
    UNITPRICE = S.UNITPRICE,
    CATEGORY = S.CATEGORY

WHEN NOT MATCHED THEN
INSERT (
    PRODUCTID,
    PRODUCT_NAME,
    UNITPRICE,
    CATEGORY
)
VALUES (
    S.PRODUCTID,
    S.PRODUCTNAME,
    S.UNITPRICE,
    S.CATEGORY
);

INSERT INTO MART.ETL_AUDIT_LOG
SELECT
    ''PRODUCT_REFRESH'',
    CURRENT_TIMESTAMP(),
    COUNT(*),
    ''SUCCESS''
FROM PRODUCT_STREAM;

RETURN ''SUCCESS'';

END;
';
create or replace stream RETAIL_DW.RAW.CUSTOMER_STREAM on table CUSTOMER_RAW;
create or replace stream RETAIL_DW.RAW.ORDERS_STREAM on table SALES_RAW;
create or replace stream RETAIL_DW.RAW.ORDER_ITEMS_STREAM on table SALES_ITEM_RAW;
create or replace stream RETAIL_DW.RAW.PRODUCT_STREAM on table PRODUCT_RAW;
create or replace task RETAIL_DW.RAW.TASK_CUSTOMER_REFRESH
	warehouse=RETAIL_WH
	schedule='USING CRON 0 * * * * UTC'
	as CALL SP_REFRESH_CUSTOMER();
create or replace schema RETAIL_DW.STAGING;

create or replace TABLE RETAIL_DW.STAGING.STG_CUSTOMER (
	CUSTOMER_ID NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(16777216),
	CITY VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	CREATEDDATE DATE
);
create or replace TABLE RETAIL_DW.STAGING.STG_ORDERS (
	ORDERID NUMBER(38,0),
	CUSTOMERID NUMBER(38,0),
	REPID NUMBER(38,0),
	ORDERDATE DATE,
	STATUS VARCHAR(150)
);
create or replace TABLE RETAIL_DW.STAGING.STG_ORDER_ITEMS (
	ITEMID NUMBER(38,0),
	ORDERID NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	QTY NUMBER(18,2),
	PRICE NUMBER(18,2),
	LINE_AMOUNT NUMBER(36,4)
);
create or replace TABLE RETAIL_DW.STAGING.STG_PRODUCT (
	PRODUCTID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	UNITPRICE NUMBER(18,2),
	CATEGORY VARCHAR(16777216)
);
CREATE OR REPLACE PROCEDURE RETAIL_DW.STAGING.SP_BUILD_DIM_CUSTOMER()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    MERGE INTO RETAIL_DW.MART.DIM_CUSTOMER T
    USING RETAIL_DW.STAGING.STG_CUSTOMER S
        ON T.CUSTOMER_ID = S.CUSTOMER_ID

    WHEN MATCHED THEN
        UPDATE SET
            CUSTOMER_NAME = S.CUSTOMER_NAME,
            CITY          = S.CITY,
            PHONE         = S.PHONE,
            STATUS        = S.STATUS

    WHEN NOT MATCHED THEN
        INSERT
        (
            CUSTOMER_ID,
            CUSTOMER_NAME,
            CITY,
            PHONE,
            STATUS
        )
        VALUES
        (
            S.CUSTOMER_ID,
            S.CUSTOMER_NAME,
            S.CITY,
            S.PHONE,
            S.STATUS
        );

    INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
    (
        PIPELINE_NAME,
        RUN_TIME,
        RECORD_COUNT,
        STATUS
    )
    VALUES
    (
        ''SP_BUILD_DIM_CUSTOMER'',
        CURRENT_TIMESTAMP(),
        NULL,
        ''SUCCESS''
    );

    RETURN ''SUCCESS'';

EXCEPTION
    WHEN OTHER THEN

        INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
        (
            PIPELINE_NAME,
            RUN_TIME,
            RECORD_COUNT,
            STATUS
        )
        VALUES
        (
            ''SP_BUILD_DIM_CUSTOMER'',
            CURRENT_TIMESTAMP(),
            NULL,
            ''FAILED''
        );

        RETURN ''FAILED: '' || SQLERRM;

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.STAGING.SP_BUILD_DIM_PRODUCT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    MERGE INTO RETAIL_DW.MART.DIM_PRODUCT T
    USING RETAIL_DW.STAGING.STG_PRODUCT S
        ON T.PRODUCTID = S.PRODUCTID

    WHEN MATCHED THEN
        UPDATE SET
            PRODUCT_NAME = S.PRODUCT_NAME,
            UNITPRICE    = S.UNITPRICE,
            CATEGORY     = S.CATEGORY

    WHEN NOT MATCHED THEN
        INSERT
        (
            PRODUCTID,
            PRODUCT_NAME,
            UNITPRICE,
            CATEGORY
        )
        VALUES
        (
            S.PRODUCTID,
            S.PRODUCT_NAME,
            S.UNITPRICE,
            S.CATEGORY
        );

    INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
    (
        PIPELINE_NAME,
        RUN_TIME,
        RECORD_COUNT,
        STATUS
    )
    VALUES
    (
        ''SP_BUILD_DIM_PRODUCT'',
        CURRENT_TIMESTAMP(),
        NULL,
        ''SUCCESS''
    );

    RETURN ''SUCCESS'';

EXCEPTION
    WHEN OTHER THEN

        INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
        (
            PIPELINE_NAME,
            RUN_TIME,
            RECORD_COUNT,
            STATUS
        )
        VALUES
        (
            ''SP_BUILD_DIM_PRODUCT'',
            CURRENT_TIMESTAMP(),
            NULL,
            ''FAILED''
        );

        RETURN ''FAILED: '' || SQLERRM;

END;
';
CREATE OR REPLACE PROCEDURE RETAIL_DW.STAGING.SP_BUILD_FACT_SALES()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN

    MERGE INTO RETAIL_DW.MART.FACT_SALES T
    USING
    (
        SELECT
            O.ORDERID,
            O.ORDERDATE,
            O.CUSTOMERID,
            I.PRODUCTID,
            I.QTY,
            I.PRICE,
            (I.QTY * I.PRICE) AS TOTAL_AMOUNT
        FROM RETAIL_DW.STAGING.STG_ORDERS O
        INNER JOIN RETAIL_DW.STAGING.STG_ORDER_ITEMS I
            ON O.ORDERID = I.ORDERID
    ) S
    ON T.ORDER_ID = S.ORDERID
    AND T.PRODUCT_ID = S.PRODUCTID

    WHEN MATCHED THEN
        UPDATE SET
            ORDER_DATE   = S.ORDERDATE,
            CUSTOMER_ID  = S.CUSTOMERID,
            QUANTITY     = S.QTY,
            UNIT_PRICE   = S.PRICE,
            TOTAL_AMOUNT = S.TOTAL_AMOUNT

    WHEN NOT MATCHED THEN
        INSERT
        (
            ORDER_ID,
            ORDER_DATE,
            CUSTOMER_ID,
            PRODUCT_ID,
            QUANTITY,
            UNIT_PRICE,
            TOTAL_AMOUNT
        )
        VALUES
        (
            S.ORDERID,
            S.ORDERDATE,
            S.CUSTOMERID,
            S.PRODUCTID,
            S.QTY,
            S.PRICE,
            S.TOTAL_AMOUNT
        );

    INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
    (
        PIPELINE_NAME,
        RUN_TIME,
        RECORD_COUNT,
        STATUS
    )
    VALUES
    (
        ''SP_BUILD_FACT_SALES'',
        CURRENT_TIMESTAMP(),
        NULL,
        ''SUCCESS''
    );

    RETURN ''SUCCESS'';

EXCEPTION
    WHEN OTHER THEN

        INSERT INTO RETAIL_DW.MART.ETL_AUDIT_LOG
        (
            PIPELINE_NAME,
            RUN_TIME,
            RECORD_COUNT,
            STATUS
        )
        VALUES
        (
            ''SP_BUILD_FACT_SALES'',
            CURRENT_TIMESTAMP(),
            NULL,
            ''FAILED''
        );

        RETURN ''FAILED: '' || SQLERRM;

END;
';